[build]
  functions = "netlify/functions"

# YENİ BÖLÜM: Fonksiyonların nasıl paketleneceğini belirliyoruz.
# Bu, Netlify'a Node.js modüllerini (crypto gibi) doğru şekilde
# işlemesini ve dahil etmesini söyler.
[functions."*"]
  node_bundler = "esbuild"
  # Bu satır, Netlify'a projenin bağımlılıklarını (package.json)
  # fonksiyona dahil etmesini zorunlu kılar.
  included_files = ["../../package.json"]
